# -*- coding: utf-8 -*-
"""basic_list.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uuXWCiuIRCD5XnNGdJcP1YsD1JD1SuN6
"""

#Python program to interchange first and last elements in a list
def interchange_first_last(lst):
    if len(lst) > 1:
        lst[0], lst[-1] = lst[-1], lst[0]
    return lst

lst = [1, 2, 3, 4, 5]
print(interchange_first_last(lst))

#Python program to swap two elements in a list
def swap_elements(lst, pos1, pos2):
    lst[pos1], lst[pos2] = lst[pos2], lst[pos1]
    return lst

lst = [1, 2, 3, 4, 5]
print(swap_elements(lst, 1, 3))

#Python – Swap elements in String list
def swap_string_elements(lst, pos1, pos2):
    lst[pos1], lst[pos2] = lst[pos2], lst[pos1]
    return lst

lst = ["apple", "banana", "cherry"]
print(swap_string_elements(lst, 0, 2))

#Python | Ways to find length of list
lst = [1, 2, 3, 4, 5]
print(len(lst))

#Maximum of two numbers in Python
def max_of_two(a, b):
    return a if a > b else b

print(max_of_two(3, 5))

#Minimum of two numbers in Python
def min_of_two(a, b):
    return a if a < b else b

print(min_of_two(3, 5))

#Python | Ways to check if element exists in list
lst = [1, 2, 3, 4, 5]
element = 3
print(element in lst)

#Different ways to clear a list in Python
lst = [1, 2, 3, 4, 5]
lst.clear()
print(lst)

#Python | Reversing a List
lst = [1, 2, 3, 4, 5]
print(lst[::-1])

#Python | Cloning or Copying a list
lst = [1, 2, 3, 4, 5]
cloned_lst = lst.copy()
print(cloned_lst)

#Python | Count occurrences of an element in a list
lst = [1, 2, 3, 1, 2, 1]
print(lst.count(1))

#Python Program to find sum and average of List in Python
lst = [1, 2, 3, 4, 5]
sum_lst = sum(lst)
avg_lst = sum_lst / len(lst)
print("Sum:", sum_lst)
print("Average:", avg_lst)

#Python | Sum of number digits in List
lst = [123, 456, 789]
sum_of_digits = sum([sum(map(int, str(num))) for num in lst])
print(sum_of_digits)

#Python | Multiply all numbers in the list
import math

lst = [1, 2, 3, 4, 5]
product = math.prod(lst)
print(product)

#Python program to find smallest number in a list
lst = [1, 2, 3, 4, 5]
print(min(lst))

#Python program to find largest number in a list
lst = [1, 2, 3, 4, 5]
print(max(lst))

#Python program to find second largest number in a list
lst = [1, 2, 3, 4, 5]
lst.sort()
print(lst[-2])

#Python program to print even numbers in a list
lst = [1, 2, 3, 4, 5, 6]
even_numbers = [num for num in lst if num % 2 == 0]
print(even_numbers)

#Python program to print odd numbers in a List
lst = [1, 2, 3, 4, 5, 6]
odd_numbers = [num for num in lst if num % 2 != 0]
print(odd_numbers)

#Python program to print all even numbers in a range
def print_even_in_range(start, end):
    even_numbers = [num for num in range(start, end + 1) if num % 2 == 0]
    print(even_numbers)

print_even_in_range(1, 10)

#Python program to print all odd numbers in a range
def print_odd_in_range(start, end):
    odd_numbers = [num for num in range(start, end + 1) if num % 2 != 0]
    print(odd_numbers)

print_odd_in_range(1, 10)

#Python program to count Even and Odd numbers in a List
lst = [1, 2, 3, 4, 5, 6]
even_count = len([num for num in lst if num % 2 == 0])
odd_count = len([num for num in lst if num % 2 != 0])
print("Even numbers count:", even_count)
print("Odd numbers count:", odd_count)

#Python program to print positive numbers in a list
lst = [-1, 2, -3, 4, -5, 6]
positive_numbers = [num for num in lst if num > 0]
print(positive_numbers)

#Python program to print negative numbers in a list
lst = [-1, 2, -3, 4, -5, 6]
negative_numbers = [num for num in lst if num < 0]
print(negative_numbers)

#Python program to print all positive numbers in a range
def print_positive_in_range(start, end):
    positive_numbers = [num for num in range(start, end + 1) if num > 0]
    print(positive_numbers)

print_positive_in_range(-10, 10)

#Python program to print all negative numbers in a range
def print_negative_in_range(start, end):
    negative_numbers = [num for num in range(start, end + 1) if num < 0]
    print(negative_numbers)

print_negative_in_range(-10, 10)

#Python program to count positive and negative numbers in a list
lst = [-1, 2, -3, 4, -5, 6]
positive_count = len([num for num in lst if num > 0])
negative_count = len([num for num in lst if num < 0])
print("Positive numbers count:", positive_count)
print("Negative numbers count:", negative_count)

#Remove multiple elements from a list in Python
def remove_elements(lst, elements_to_remove):
    return [num for num in lst if num not in elements_to_remove]

lst = [1, 2, 3, 4, 5]
elements_to_remove = [2, 4]
print(remove_elements(lst, elements_to_remove))

#Python Remove empty tuples from a list
lst = [(1, 2), (), (3, 4), (), (5,)]
lst = [tup for tup in lst if tup]
print(lst)

#Python Program to print duplicates from a list of integers
def print_duplicates(lst):
    seen = set()
    duplicates = set()
    for num in lst:
        if num in seen:
            duplicates.add(num)
        else:
            seen.add(num)
    print(duplicates)

lst = [1, 2, 3, 2, 4, 5, 1]
print_duplicates(lst)